# Dockerfile.dev
FROM docker.io/library/ruby:4.0.6-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      libvips \
      libyaml-dev \
      pkg-config \
      sqlite3 && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

ENV BUNDLE_PATH="/usr/local/bundle"

COPY Gemfile Gemfile.lock ./
RUN bundle install && gem install foreman --version 0.90.0 --no-document

COPY . .

EXPOSE 3000
CMD ["bin/dev"]
