service: portfolio
image: portfolio

servers:
  web:
    - <%= ENV.fetch("DEPLOY_HOST") %>

proxy:
  ssl: true
  host: <%= ENV.fetch("APP_HOST") %>
  app_port: 80
  healthcheck:
    interval: 5
    path: /up
    timeout: 5

registry:
  server: localhost:5555

ssh:
  user: deploy

volumes:
  - /var/lib/portfolio/storage:/rails/storage

asset_path: /rails/public/assets

boot:
  limit: 1
  wait: 2

builder:
  arch: amd64

logging:
  driver: local
  options:
    max-size: 10m
    max-file: 5

env:
  clear:
    APP_HOST: <%= ENV.fetch("APP_HOST") %>
    SMTP_ADDRESS: <%= ENV.fetch("SMTP_ADDRESS") %>
    SMTP_PORT: <%= ENV.fetch("SMTP_PORT") %>
    SMTP_DOMAIN: <%= ENV.fetch("SMTP_DOMAIN") %>
    MAILER_FROM: <%= ENV.fetch("MAILER_FROM") %>
    SOLID_QUEUE_IN_PUMA: "true"
    RAILS_LOG_LEVEL: info
  secret:
    - RAILS_MASTER_KEY
    - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
    - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
    - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
    - SMTP_USERNAME
    - SMTP_PASSWORD

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
